const express = require("express");
const dotenv = require("dotenv");
const connectDB = require("./configs/db.js");
const authRoutes = require("./routes/authRouter.js");
const cors = require("cors");
const uploadRoutes = require("./routes/uploadRouter");
const decodeRoute = require("./routes/decodeTokenRoute.js");
const searchDonorRoute = require("./routes/FindDonors");
const suggesstionroute = require("./routes/SuggestionsRoute");
const requestroute = require("./routes/requestRouter.js");
const adminLogin = require("./routes/adminroute.js");
const getSuggestions = require("./routes/getSuggestionroute.js");
const getDonor = require("./routes/getdonorroute.js");
const fetchadminData = require("./routes/fetchAdmindata.js");
const getData = require("./routes/getRequests");
const deleteSuggestions = require("./routes/deleteSuggestion.js");
const deleteReq = require("./routes/deleteReq");
const deleteDonor = require("./routes/deleteDonor.js");
const verifyAdmin = require("./middlewares/VerifyAdmin");
const updateRequest = require("./routes/ChangeRequestStatus.js");
const Myrequest = require("./routes/getUserRequestStatus.js");
const userSettingsRoutes = require("./routes/updateProfile.js");
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
const PORT = process.env.PORT || 8080;
app.get("/", (req, res) => {
  res.json({ message: "server is running..." });
});
const announcementRoutes = require("./routes/announcement.route.js");
app.use("/announcement", announcementRoutes);
app.use("/api/auth", authRoutes);
app.use("/api/file", uploadRoutes);
app.use("/api/decode", decodeRoute);
app.use("/api", searchDonorRoute, suggesstionroute);
app.use("/api/request", requestroute);
app.use("/api/req", adminLogin);
app.use("/api/suggestions", getSuggestions);
app.use("/api/get", getDonor);
app.use("/api/admin", fetchadminData);
app.use("/get", getData);
app.use("/delete", deleteSuggestions);
app.use("/delete/req", deleteReq);
app.use("/delete/donor", deleteDonor);
app.use("/update", updateRequest);
app.use("/my-req", Myrequest);

app.use("/user", userSettingsRoutes);
connectDB();
app.listen(PORT, () => {
  console.log(`server is running at ${PORT}`);
});
